spring:
  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:2525}
    username: ${SMTP_USER:}
    password: ${SMTP_PASS:}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  elasticsearch:
    uris: ${ELASTIC_URI:http://elasticsearch:9200}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:kafka:9092}
    consumer:
      group-id: ${app.kafka.group-id}
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
    producer:
      properties:
        spring.json.add.type.headers: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_JWKS_URI:http://auth-server:9000/oauth2/jwks}

app:
  kafka:
    topic: email.send
    group-id: email-service
